# Generated by Django 6.0.4 on 2026-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
