# Generated by Django 6.0.4 on 2026-06-14 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.PositiveIntegerField(default=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacidade Semanal',
                'verbose_name_plural': 'Capacidade Semanal',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='estado',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('diagnostico', 'Em Diagnóstico'), ('reparacao', 'Em Reparação'), ('pronta', 'Pronta'), ('entregue', 'Entregue')], default='recebida', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='token_tracking',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
    ]
