# Generated by Django 6.0.4 on 2026-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_capacidadesemanal_booking_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='estado',
            field=models.CharField(choices=[('marcada', 'Marcação Efetuada'), ('recebida', 'Recebida'), ('diagnostico', 'Em Diagnóstico'), ('reparacao', 'Em Reparação'), ('pronta', 'Pronta'), ('entregue', 'Entregue')], default='marcada', max_length=20),
        ),
    ]
